from .painter import (
    DEFAULT_FONT,
    Color,
    LinearGradient,
)
from .plot import (
    Canvas,
    Frame,
    RandomTriangleBg,
    RoundRectBg,
    TextBox,
    TextStyle,
)

SEKAI_BLUE_BG = RandomTriangleBg(True)
SEKAI_RED_BG = RandomTriangleBg(False, main_hue=0.05)

BG_PADDING = 20
WIDGET_BG_COLOR = (255, 255, 255, 150)
WIDGET_BG_RADIUS = 10
DIFF_COLORS = {
    "easy": (102, 221, 17, 255),
    "normal": (51, 187, 238, 255),
    "hard": (255, 170, 0, 255),
    "expert": (238, 68, 102, 255),
    "master": (187, 51, 238, 255),
    "append": LinearGradient((182, 144, 247, 255), (243, 132, 220, 255), (0, 0), (1, 1)),
}

PLAY_RESULT_COLORS = {
    "not_clear": (69, 67, 104, 255),
    "clear": (255, 226, 118, 255),
    "fc": (253, 167, 249, 255),
    "ap": (63, 230, 228, 255),
}

DEFAULT_WATERMARK = "Designed by Lunacha, generated by HarukiBot NEO"

CHARACTER_COLOR_CODE = {
    1: "#33aaee",
    2: "#ffdd44",
    3: "#ee6666",
    4: "#bbdd22",
    5: "#ffccaa",
    6: "#99ccff",
    7: "#ffaacc",
    8: "#99eedd",
    9: "#ff6699",
    10: "#00bbdd",
    11: "#ff7722",
    12: "#0077dd",
    13: "#ffbb00",
    14: "#ff66bb",
    15: "#33dd99",
    16: "#bb88ee",
    17: "#bb6688",
    18: "#8888cc",
    19: "#ccaa88",
    20: "#ddaacc",
    21: "#33ccbb",
    22: "#ffcc11",
    23: "#ffee11",
    24: "#ffbbcc",
    25: "#dd4444",
    26: "#3366cc",
    27: "#33ccbb",
    28: "#33ccbb",
    29: "#33ccbb",
    30: "#33ccbb",
    31: "#33ccbb",
    32: "#ffcc11",
    33: "#ffcc11",
    34: "#ffcc11",
    35: "#ffcc11",
    36: "#ffcc11",
    37: "#ffee11",
    38: "#ffee11",
    39: "#ffee11",
    40: "#ffee11",
    41: "#ffee11",
    42: "#ffbbcc",
    43: "#ffbbcc",
    44: "#ffbbcc",
    45: "#ffbbcc",
    46: "#ffbbcc",
    47: "#dd4444",
    48: "#dd4444",
    49: "#dd4444",
    50: "#dd4444",
    51: "#dd4444",
    52: "#3366cc",
    53: "#3366cc",
    54: "#3366cc",
    55: "#3366cc",
    56: "#3366cc",
}


def roundrect_bg(
    fill: Color = WIDGET_BG_COLOR,
    radius: int = WIDGET_BG_RADIUS,
    alpha: int | None = None,
    blur_glass: bool | None = None,
    blur_glass_kwargs: dict = {},
):
    """
    统一的半透明白色圆角矩形背景
    """
    if blur_glass is None:
        blur_glass = True
    if alpha is not None:
        fill = (*fill[:3], alpha)
    return RoundRectBg(fill, radius, blur_glass=blur_glass, blur_glass_kwargs=blur_glass_kwargs)


def add_watermark(canvas: Canvas, text: str = DEFAULT_WATERMARK, size=12):
    """
    在画布上添加水印
    """
    frame_watermark = Frame().set_content_align("rb").set_padding(0)
    frame_canvas = Frame().set_content_align(canvas.get_content_align()).set_padding(0).set_size((canvas.w, canvas.h))
    s1 = TextStyle(font=DEFAULT_FONT, size=size, color=(255, 255, 255, 256))
    s2 = TextStyle(font=DEFAULT_FONT, size=size, color=(75, 75, 75, 256))
    offset1 = (int(16 - BG_PADDING * 0.5), 16)
    offset2 = (offset1[0] + 1, offset1[1] + 1)
    text1 = TextBox(text, style=s1).set_omit_parent_bg(True).set_offset(offset1)
    text2 = TextBox(text, style=s2).set_omit_parent_bg(True).set_offset(offset2)
    items = canvas.items
    canvas.set_items([])
    canvas.set_padding(BG_PADDING)
    for item in items:
        frame_canvas.add_item(item)
    frame_watermark.add_item(frame_canvas)
    frame_watermark.add_item(text2)
    frame_watermark.add_item(text1)
    canvas.add_item(frame_watermark).set_size(None)
